### PR TITLE
Support webhook secrets

### PR DESCRIPTION
**Pull request by pathmissing**
Adds support for GitHub webhook secrets to prevent unauthorized requests from triggering syncs. Other providers will follow soon.

### CODE REVIEW

**Comment by pathmissing** [comment]
Resolves #72

**Comment by pathmissing** [comment]
Works with Gitlab secret tokens. Contrary to Github, Gitlab does not hash the payload with the secret to create a signature. Instead, they send the whole token in plaintext, which is not a good implementation. This problem is already referenced [here](https://gitlab.com/gitlab-org/gitlab-ce/issues/37380).

**Comment by pathmissing** [comment]
Bitbucket does not support webhook tokens yet. I'll make sure to add support when they [decide to do](https://bitbucket.org/site/master/issues/14683/add-webhook-secret).

**Comment by pathmissing** [comment]
To do: Add field for webhook secret to wizard

**Comment by w00fz** [comment]
This looks good! Is the wizard the only missing portion? (Aside from bitbucket).
Although not as secure, my initial thought was to have a simple plaintext password field to use with  the webhook `&passcode=foobar` this would be at least add a minimum layer of protection and make it harder to guess.
Perhaps something useful to temporary address bitbucket.

**Comment by pathmissing** [comment]
To my knowledge, the field for the webhook secret in the wizard is the only thing missing. 
I think using a randomly generated string for the webhook url would achieve the same thing as having a passcode query param. Maybe the webhook url should be random by default :)

**Pull request merged**
