### PR TITLE
documented support for generic git - issue:7

### PR DESCRIPTION
**Pull request by erlepereira**
Have added a bit of markup as discussed. I have kept it minimal, with a view that this would probably work in the larger number of other git solution, but it is upto the user of the said git solution to do a bit more. At the least it probably tells the user "hey this should work on your git too"

not sure if more relevant copy changes are preferred instead of what I have added.

gitsync_w1
gitsync_w2
gitsync_w3

other dev related changes:
* have added a generic git logo -- picked from https://en.wikipedia.org/wiki/File:Git-logo.svg
* needed to updated webpack.conf.js --- uses "babel-loader" instead of "babel"

### CODE REVIEW

**Comment by w00fz** [comment]
Wow nice job! This looks awesome.
I'll review this tomorrow as well as other issues and PR so I can get a release out soon.

Thank you so much for this!

**Comment by paulhibbitts** [comment]
Hi @erlepereira @w00fz this looks like a great addition to the plugin! I've got a few minor suggestions to help keep the complexity of the wizard choices to a minimum for non-dev types:

1) Remove the bracketed text next to the Git graphic ("Generic solution"). I think this option, aimed at devs more, needs less explanation and not more.
2) Remove the text 'Any other Git solution with Webhook capability'. Again, as this option is aimed at dev I would prefer not to draw excessive attention to it by having a lot of explanation text.

And finally, now with a 'Git' choice, users may also get confused that they are always asked for a 'Git User' and' Git Password' even with choices like GitHub or GitLab made. Perhaps just 'Username' and 'Password' or modifying the text to match the choice, i.e. 'GitHub Username' and 'GitHub Password'?

Just some suggestions and thoughts for your review, please let me know what you both think.

Thanks very much,
Paul

**Comment by w00fz** [comment]
Maybe instead of Generic solution it could say "Others...".
I'm actually thinking that removing the paragraph below it would make it even more confusing because Git is very generic.
Perhaps that paragraph can be expanded just a little more, something like "Any other git solution, including self-hosted and with webhooks capability".
We can make that paragraph hidden as well, and only ever show if you actually select the Git option.

I just feel like this 3rd option should be equally visible and important as the other 3 main ones. I want to make obvious and clear from the Wizard that those 3 are not the only supported hosting services. As you can see in #7 this wasn't entirely clear because it does look like you can only choose between GitHub, BitBucket or GitLab.

I think as a last option in the stack, this would not confuse the lesser expert users because most likely they use one of the 3 above and won't even care about what follows.

Regarding the Git User and Git Password, I honestly don't think that would be confusing but I can make it so that the Git portion reflects the provider selected like you suggested.
So it would dynamically change to GitHub User or GitLab User etc.

**Comment by erlepereira** [comment]
Hi, great ideas. I was wondering about the same points too, but as mentioned the  idea is to indicate a broader capability. my thoughts is to use below:

 Key here is to indicate somehow on the first wizard screen, what this 4th option is. Broader capability, other git solutions for the more advanced user, while retaining the simplicity.

1. use "_others_" instead of Generic
2.  "_Any other git solution, including self-hosted and with webhooks capability_"
3. Wondering about Git logo + generic too... the idea was to highlight the broader capability of this plugin.

-- use some indication in the logo .. attached a quick mockup here
git-othermockup svg

**Comment by paulhibbitts** [comment]
Thanks for your ideas/suggestions @w00fz (esp suggestion of "other") @erlepereira , and I really like the direction of the new mockup! How about a few more tweaks like those shown below? 

mockup 2

I think with the above the field names of username/password do not need to be dynamic.

Looking forward to hear your thoughts.

Thanks very much,
Paul

**Comment by w00fz** [comment]
I like that! 👍

// Djamil Legato // From iPhone //

**Comment by erlepereira** [comment]
Yup, Love it. Latest commit makes it look identical to the mockup -- please review the scss code ....( not my strongpoint ) @w00fz  @paulhibbitts

**Comment by paulhibbitts** [comment]
Awesome, thanks so much @erlepereira! I'll keep my fingers crossed with what @w00fz says🙂

**Pull request merged**
